version: '3.3'

services:

  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: ./
    image: catswhocode/api:latest
    container_name: catswhocode_api
    ports:
      - '8000'
    networks:
      - frontend
    env_file:
      - app/app.env

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./docker/frontend
    image: catswhocode/frontend:latest
    container_name: catswhocode_frontend
    ports:
      - '80:8080'
    depends_on:
      - api
    networks:
      - frontend

networks:
  frontend:
