site_name: Cats Who Code Docs

theme: readthedocs

markdown_extensions:
    - toc:
        permalink: []
    - admonition:
    - markdown_newtab: 

pages:
- Home: 'index.md'
- Running the App Standalone: 'run-app-locally.md'
- Running the App in Production: 'run-app-production.md'
- For Django Developers working on Cats Who Code: 'local-dev-setup.md'

